version: "3"
name: recrit-dev
services:
  kafka:
    # reference: https://hub.docker.com/r/bitnami/kafka
    image: 'bitnami/kafka:latest'
    # recrit 과 kafka 가 같은 docker network 에서 동작한다면 이 설정 사용
    # ports:
    #   - '9092:9092'
    # environment:
    #   - KAFKA_CFG_NODE_ID=0
    #   - KAFKA_CFG_PROCESS_ROLES=controller,broker
    #   - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
    #   - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
    #   - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
    #   - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER

    # recrit 이 로컬 호스트머신에서 동작하고 kafka 가 docker container 에서 동작한다면 이 설정 사용
    # reference: https://hub.docker.com/r/bitnami/kafka - "Accessing Apache Kafka with internal and external clients"
    ports:
      - '9094:9094'
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER

  # TODO: Add postgresql
  # TODO: Add neo4j
  # TODO: Add elasticsearch & kibana (?)